task: pretrain
is_train: true
architecture: probe
batch_size: 512
input_len: 30
pred_len: 25
d_model: 256
nhead: 8
e_layers: 6
d_layers: 6
dropout: 0.1
learning_rate: 0.01
warmup_steps: 800
pos_emb: 'nrml'
