task: pretrain
is_train: true
architecture: selfregression
batch_size: 1024
input_len: 30
pred_len: 30
d_model: 256
nhead: 8
e_layers: 6
d_layers: 6
dropout: 0.1
learning_rate: 0.01
warmup_steps: 400
pos_emb: 'nrml'
